name: pdfenv
channels:
- conda-forge
- defaults
dependencies:
- numpy=1.21.2
- matplotlib=3.5
- netCDF4=1.5.7
- numexpr=2.8.1
- pandas=1.3.5
- scipy=1.7.3
- setuptools=58.0.4
- Shapely=1.7.1
- gsw=3.4.0
- python-dateutil=2.8.2
